### ISSUE TITLE
Support new Tailwind colors

### ISSUE THREAD

**Issue by Aarbel** [Ankcorn/Tailwind-Colors#1]
@Ankcorn do you plan to support new tailwind colors ? (slate, etc...)

https://tailwindcss.com/docs/customizing-colors

**Comment by Ankcorn** [comment]
I didn't realise anyone else was interested in this 😱 I think the whole pallet is outdated now. I haven't been using it too much recently. Feel free to take it and update it if you want. If you end up publishing it I can hand over the npm name if you want it.

**Comment by ImBaedin** [comment]
@Aarbel This may not be your use-case, but if you're already using tailwind in the project the colors can be imported directly:
![image](https://user-images.githubusercontent.com/7637729/153341415-a2f0d795-da82-4b0d-a022-fe2ae52bb109.png)

As for this repo, you could easily copy the [color file](https://github.com/tailwindlabs/tailwindcss/blob/b8cda161dd0993083dcef1e2a03988c70be0ce93/src/public/colors.js) directly from the tailwind repo, or add it as a dev dependency here. Then you could set up rollup or something to pass through the value. May be against Tailwind license or something though.
